name: docker-build

on: [push, pull_request]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Clone and checkout branch
              uses: actions/checkout@v2

            - name: Build docker image
              run: docker build -t test-tag .